# Site settings
title: Tarini Konchady
description: Taini Konchady
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tkonchady.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Tarini Konchady
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: Astronomy Graduate Student at Texas A&M University
email: anon@anon.com
twitter_username: lorem_ipsum
github_username:  lorem_ipsum
linkedin_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
