# Site settings
title: Tarini Konchady
description: Taini Konchady
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tkonchady.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Tarini Konchady
user_description: I am a first-year graduate student at Texas A&M working under Dr. Lucas Macri. My research is on using Mira variables to better calibrate the extragalactic distance ladder. Outside of research, I am involved in 
user_title: Astronomy Graduate Student at Texas A&M University
email: tkonchady@tamu.edu
twitter_username: sirius_stargaze
github_username:  tkonchady
#linkedin_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
